cout << "Chon 1 trong cac yeu cau sau: \n";
    // cout << "1. In ra chuoi so theo thu tu tang dan.\n";
    // cout << "2. In ra chuoi so theo thu tu giam dan.\n";
    // cout << "3. In ra so lon nhat, nho nhat trong chuoi da nhap.\n";
    // cout << "4. Nhap them 1 so sau do chen vao dung vi tri da sap xep trong mang.\n";
    // cout << "5. Nhap vao vi tri can xoa, sau do xoa phan tu mang tai vi tri do.\n";
    // cout << "6. Nhap vao gia tri, tim kiem gia tri do trong mang da nhap.\n";
    // cout << "7. Nhap so k (k<N), tach mang b thanh 2 mang b1, b2.\n";
    // cout << "8. Tach mang b thanh 2 mang: mang b1: chua so nguyen am, mang b2: chua so nguyen duong. \n";